-- Create syntax for TABLE 'rawAsjc'
CREATE TABLE IF NOT EXISTS `rawAsjc` (
  `description` varchar(255) DEFAULT NULL,
  `code` varchar(255) DEFAULT NULL,
  KEY `codeIndx` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Create syntax for TABLE 'rawConferenceProceedings'
CREATE TABLE IF NOT EXISTS `rawConferenceProceedings` (
  `sourceRecordId` varchar(255) DEFAULT NULL,
  `sourceTitle` varchar(255) DEFAULT NULL,
  `coverage` varchar(255) DEFAULT NULL,
  `issn` varchar(255) DEFAULT NULL,
  `addedNovember2015` varchar(255) DEFAULT NULL,
  `snip2013` varchar(255) DEFAULT NULL,
  `ipp2013` varchar(255) DEFAULT NULL,
  `sjr2013` varchar(255) DEFAULT NULL,
  `snip2014` varchar(255) DEFAULT NULL,
  `ipp2014` varchar(255) DEFAULT NULL,
  `sjr2014` varchar(255) DEFAULT NULL,
  `snip2015` varchar(255) DEFAULT NULL,
  `ipp2015` varchar(255) DEFAULT NULL,
  `sjr2015` varchar(255) DEFAULT NULL,
  `asjc` varchar(255) DEFAULT NULL,
  KEY `sourceRecordIdIndx` (`sourceRecordId`),
  KEY `issnIndx` (`issn`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Create syntax for TABLE 'rawConferenceProceedingsBackfiles'
CREATE TABLE IF NOT EXISTS `rawConferenceProceedingsBackfiles` (
  `sourceRecordId` varchar(255) DEFAULT NULL,
  `sourceTitle` varchar(255) DEFAULT NULL,
  `coverage` varchar(255) DEFAULT NULL,
  `issn` varchar(255) DEFAULT NULL,
  `asjc` varchar(255) DEFAULT NULL,
  KEY `sourceRecordIdIndx` (`sourceRecordId`),
  KEY `issnIndx` (`issn`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `rawCwts` (
  `title` varchar(255) DEFAULT NULL,
  `type` varchar(255) DEFAULT NULL,
  `issn` varchar(255) DEFAULT NULL,
  `eIssn` varchar(255) DEFAULT NULL,
  `asjc` varchar(255) DEFAULT NULL,
  `year` varchar(255) DEFAULT NULL,
  `citingSource` varchar(255) DEFAULT NULL,
  `pValue` varchar(255) DEFAULT NULL,
  `ipp` varchar(255) DEFAULT NULL,
  `ippLowerBound` varchar(255) DEFAULT NULL,
  `ippUpperBound` varchar(255) DEFAULT NULL,
  `snip` varchar(255) DEFAULT NULL,
  `snipLowerBound` varchar(255) DEFAULT NULL,
  `snipUpperBound` varchar(255) DEFAULT NULL,
  `percentSelfCite` varchar(255) DEFAULT NULL,
  KEY `issnIndx` (`issn`),
  KEY `eIssnIndx` (`eIssn`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Create syntax for TABLE 'rawScimago'
CREATE TABLE IF NOT EXISTS `rawScimago` (
  `rank` varchar(255) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `type` varchar(255) DEFAULT NULL,
  `issn` varchar(255) DEFAULT NULL,
  `sjr` varchar(255) DEFAULT NULL,
  `sjrBestQuartile` varchar(255) DEFAULT NULL,
  `hIndex` varchar(255) DEFAULT NULL,
  `totalDocs2015` varchar(255) DEFAULT NULL,
  `totalDocs3Years` varchar(255) DEFAULT NULL,
  `totalRefs` varchar(255) DEFAULT NULL,
  `totalCites3Years` varchar(255) DEFAULT NULL,
  `citableDocs3Years` varchar(255) DEFAULT NULL,
  `citesPerDoc2Years` varchar(255) DEFAULT NULL,
  `refsPerDoc` varchar(255) DEFAULT NULL,
  `country` varchar(255) DEFAULT NULL,
  KEY `issnIndx` (`issn`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Create syntax for TABLE 'rawScopusSources'
CREATE TABLE IF NOT EXISTS `rawScopusSources` (
  `sourceRecordId` varchar(255) DEFAULT NULL,
  `sourceTitle` varchar(255) DEFAULT NULL,
  `issn` varchar(255) DEFAULT NULL,
  `eIssn` varchar(255) DEFAULT NULL,
  `coverage` varchar(255) DEFAULT NULL,
  `status` varchar(255) DEFAULT NULL,
  `snip2013` varchar(255) DEFAULT NULL,
  `ipp2013` varchar(255) DEFAULT NULL,
  `sjr2013` varchar(255) DEFAULT NULL,
  `snip2014` varchar(255) DEFAULT NULL,
  `ipp2014` varchar(255) DEFAULT NULL,
  `sjr2014` varchar(255) DEFAULT NULL,
  `snip2015` varchar(255) DEFAULT NULL,
  `ipp2015` varchar(255) DEFAULT NULL,
  `sjr2015` varchar(255) DEFAULT NULL,
  `medlineSourced` varchar(255) DEFAULT NULL,
  `openAccess` varchar(255) DEFAULT NULL,
  `articlesInPress` varchar(255) DEFAULT NULL,
  `addedMay2016` varchar(255) DEFAULT NULL,
  `sourceType` varchar(255) DEFAULT NULL,
  `titleHistoryIndication` varchar(255) DEFAULT NULL,
  `relatedTitle1` varchar(255) DEFAULT NULL,
  `relatedTitle2` varchar(255) DEFAULT NULL,
  `relatedTitle3` varchar(255) DEFAULT NULL,
  `relatedTitle4` varchar(255) DEFAULT NULL,
  `publisher` varchar(255) DEFAULT NULL,
  `publisherImprints` varchar(255) DEFAULT NULL,
  `publicationLocation` varchar(255) DEFAULT NULL,
  `asjc` varchar(255) DEFAULT NULL,
  `topLevelLifeSciences` varchar(255) DEFAULT NULL,
  `topLevelSocialSciences` varchar(255) DEFAULT NULL,
  `topLevelPhysicalSciences` varchar(255) DEFAULT NULL,
  `topLevelHealthSciences` varchar(255) DEFAULT NULL,
  `general` varchar(255) DEFAULT NULL,
  `agriculturalBiologicalSciences` varchar(255) DEFAULT NULL,
  `artsHumanities` varchar(255) DEFAULT NULL,
  `biochemistryGeneticsMolecularBiology` varchar(255) DEFAULT NULL,
  `businessManagementAccounting` varchar(255) DEFAULT NULL,
  `chemicalEngineering` varchar(255) DEFAULT NULL,
  `chemistry` varchar(255) DEFAULT NULL,
  `computerScience` varchar(255) DEFAULT NULL,
  `decisionSciences` varchar(255) DEFAULT NULL,
  `earthPlanetarySciences` varchar(255) DEFAULT NULL,
  `economicsEconometricsFinance` varchar(255) DEFAULT NULL,
  `energy` varchar(255) DEFAULT NULL,
  `engineering` varchar(255) DEFAULT NULL,
  `environmentalScience` varchar(255) DEFAULT NULL,
  `immunologyMicrobiology` varchar(255) DEFAULT NULL,
  `materialsScience` varchar(255) DEFAULT NULL,
  `mathematics` varchar(255) DEFAULT NULL,
  `medicine` varchar(255) DEFAULT NULL,
  `neuroscience` varchar(255) DEFAULT NULL,
  `nursing` varchar(255) DEFAULT NULL,
  `pharmacologyToxicologyPharmaceutics` varchar(255) DEFAULT NULL,
  `physicsAstronomy` varchar(255) DEFAULT NULL,
  `psychology` varchar(255) DEFAULT NULL,
  `socialSciences` varchar(255) DEFAULT NULL,
  `veterinary` varchar(255) DEFAULT NULL,
  `dentistry` varchar(255) DEFAULT NULL,
  `healthProfessions` varchar(255) DEFAULT NULL,
  KEY `sourceRecordIdIndx` (`sourceRecordId`),
  KEY `issnIndx` (`issn`),
  KEY `eIssnIndx` (`eIssn`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Create syntax for TABLE 'rawSfx'
CREATE TABLE IF NOT EXISTS `rawSfx` (
  `sortableTitle` varchar(255) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `titleNonFilingCharacter` varchar(255) DEFAULT NULL,
  `issn` varchar(255) DEFAULT NULL,
  `objectId` varchar(255) DEFAULT NULL,
  `targetPublicName` varchar(255) DEFAULT NULL,
  `threshold` varchar(255) DEFAULT NULL,
  `eIssn` varchar(255) DEFAULT NULL,
  `abbreviatedTitle` varchar(255) DEFAULT NULL,
  `targetServiceType` varchar(255) DEFAULT NULL,
  `lccn` varchar(255) DEFAULT NULL,
  `objectPortfolioId` varchar(255) DEFAULT NULL,
  `856u` varchar(255) DEFAULT NULL,
  `856y` varchar(255) DEFAULT NULL,
  `856a` varchar(255) DEFAULT NULL,
  `245h` varchar(255) DEFAULT NULL,
  `localThreshold` varchar(255) DEFAULT NULL,
  `globalThreshold` varchar(255) DEFAULT NULL,
  `targetId` varchar(255) DEFAULT NULL,
  `targetServiceId` varchar(255) DEFAULT NULL,
  `objectPortfolioId2` varchar(255) DEFAULT NULL,
  `categories` varchar(255) DEFAULT NULL,
  `localAttribute` varchar(255) DEFAULT NULL,
  `isbn` varchar(255) DEFAULT NULL,
  `eIsbn` varchar(255) DEFAULT NULL,
  `publisher` varchar(255) DEFAULT NULL,
  `publicationLocation` varchar(255) DEFAULT NULL,
  `publicationDate` varchar(255) DEFAULT NULL,
  `objectType` varchar(255) DEFAULT NULL,
  `activationStatus` varchar(255) DEFAULT NULL,
  `instituteId` varchar(255) DEFAULT NULL,
  `instituteName` varchar(255) DEFAULT NULL,
  `instituteAvailability` varchar(255) DEFAULT NULL,
  `language` varchar(255) DEFAULT NULL,
  `mainTitleCjk` varchar(255) DEFAULT NULL,
  `fullOriginalTitleCjk` varchar(255) DEFAULT NULL,
  `additionalIsbns` varchar(255) DEFAULT NULL,
  `additionalEIsbns` varchar(255) DEFAULT NULL,
  `author` varchar(255) DEFAULT NULL,
  `owner` varchar(255) DEFAULT NULL,
  `thresholdLocal` varchar(255) DEFAULT NULL,
  `parseParam` varchar(255) DEFAULT NULL,
  `isFree` varchar(255) DEFAULT NULL,
  KEY `issnIndx` (`issn`),
  KEY `eIssnIndx` (`eIssn`),
  KEY `lccnIndx` (`lccn`),
  KEY `objectId` (`objectId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Create syntax for TABLE 'rawSnip'
CREATE TABLE IF NOT EXISTS `rawSnip` (
  `sourceRecordId` varchar(255) DEFAULT NULL,
  `sourceTitle` varchar(255) DEFAULT NULL,
  `issn` varchar(10) DEFAULT NULL,
  `eIssn` varchar(10) DEFAULT NULL,
  `publisher` varchar(255) DEFAULT NULL,
  `publisherImprints` varchar(255) DEFAULT NULL,
  `publicationLocation` varchar(255) DEFAULT NULL,
  `snip1999` varchar(10) DEFAULT NULL,
  `ipp1999` varchar(10) DEFAULT NULL,
  `sjr1999` varchar(10) DEFAULT NULL,
  `snip2000` varchar(10) DEFAULT NULL,
  `ipp2000` varchar(10) DEFAULT NULL,
  `sjr2000` varchar(10) DEFAULT NULL,
  `snip2001` varchar(10) DEFAULT NULL,
  `ipp2001` varchar(10) DEFAULT NULL,
  `sjr2001` varchar(10) DEFAULT NULL,
  `snip2002` varchar(10) DEFAULT NULL,
  `ipp2002` varchar(10) DEFAULT NULL,
  `sjr2002` varchar(10) DEFAULT NULL,
  `snip2003` varchar(10) DEFAULT NULL,
  `ipp2003` varchar(10) DEFAULT NULL,
  `sjr2003` varchar(10) DEFAULT NULL,
  `snip2004` varchar(10) DEFAULT NULL,
  `ipp2004` varchar(10) DEFAULT NULL,
  `sjr2004` varchar(10) DEFAULT NULL,
  `snip2005` varchar(10) DEFAULT NULL,
  `ipp2005` varchar(10) DEFAULT NULL,
  `sjr2005` varchar(10) DEFAULT NULL,
  `snip2006` varchar(10) DEFAULT NULL,
  `ipp2006` varchar(10) DEFAULT NULL,
  `sjr2006` varchar(10) DEFAULT NULL,
  `snip2007` varchar(10) DEFAULT NULL,
  `ipp2007` varchar(10) DEFAULT NULL,
  `sjr2007` varchar(10) DEFAULT NULL,
  `snip2008` varchar(10) DEFAULT NULL,
  `ipp2008` varchar(10) DEFAULT NULL,
  `sjr2008` varchar(10) DEFAULT NULL,
  `snip2009` varchar(10) DEFAULT NULL,
  `ipp2009` varchar(10) DEFAULT NULL,
  `sjr2009` varchar(10) DEFAULT NULL,
  `snip2010` varchar(10) DEFAULT NULL,
  `ipp2010` varchar(10) DEFAULT NULL,
  `sjr2010` varchar(10) DEFAULT NULL,
  `snip2011` varchar(10) DEFAULT NULL,
  `ipp2011` varchar(10) DEFAULT NULL,
  `sjr2011` varchar(10) DEFAULT NULL,
  `snip2012` varchar(10) DEFAULT NULL,
  `ipp2012` varchar(10) DEFAULT NULL,
  `sjr2012` varchar(10) DEFAULT NULL,
  `snip2013` varchar(10) DEFAULT NULL,
  `ipp2013` varchar(10) DEFAULT NULL,
  `sjr2013` varchar(10) DEFAULT NULL,
  `snip2014` varchar(10) DEFAULT NULL,
  `ipp2014` varchar(10) DEFAULT NULL,
  `sjr2014` varchar(10) DEFAULT NULL,
  `snip2015` varchar(10) DEFAULT NULL,
  `ipp2015` varchar(10) DEFAULT NULL,
  `sjr2015` varchar(10) DEFAULT NULL,
  `topLevelLifeSciences` varchar(255) DEFAULT NULL,
  `topLevelSocialSciences` varchar(255) DEFAULT NULL,
  `topLevelPhysicalSciences` varchar(255) DEFAULT NULL,
  `topLevelHealthSciences` varchar(255) DEFAULT NULL,
  `general` varchar(255) DEFAULT NULL,
  `agriculturalBiologicalSciences` varchar(255) DEFAULT NULL,
  `artsHumanities` varchar(255) DEFAULT NULL,
  `biochemistryGeneticsMolecularBiology` varchar(255) DEFAULT NULL,
  `businessManagementAccounting` varchar(255) DEFAULT NULL,
  `chemicalEngineering` varchar(255) DEFAULT NULL,
  `chemistry` varchar(255) DEFAULT NULL,
  `computerScience` varchar(255) DEFAULT NULL,
  `decisionSciences` varchar(255) DEFAULT NULL,
  `earthPlanetarySciences` varchar(255) DEFAULT NULL,
  `economicsEconometricsFinance` varchar(255) DEFAULT NULL,
  `energy` varchar(255) DEFAULT NULL,
  `engineering` varchar(255) DEFAULT NULL,
  `environmentalScience` varchar(255) DEFAULT NULL,
  `immunologyMicrobiology` varchar(255) DEFAULT NULL,
  `materialsScience` varchar(255) DEFAULT NULL,
  `mathematics` varchar(255) DEFAULT NULL,
  `medicine` varchar(255) DEFAULT NULL,
  `neuroscience` varchar(255) DEFAULT NULL,
  `nursing` varchar(255) DEFAULT NULL,
  `pharmacologyToxicologyPharmaceutics` varchar(255) DEFAULT NULL,
  `physicsAstronomy` varchar(255) DEFAULT NULL,
  `psychology` varchar(255) DEFAULT NULL,
  `socialSciences` varchar(255) DEFAULT NULL,
  `veterinary` varchar(255) DEFAULT NULL,
  `dentistry` varchar(255) DEFAULT NULL,
  `healthProfessions` varchar(255) DEFAULT NULL,
  `asjc` varchar(255) DEFAULT NULL,
  KEY `issnIndx` (`issn`),
  KEY `eIssnIndx` (`eIssn`),
  KEY `sourceRecordIdIndx` (`sourceRecordId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Create syntax for TABLE `rawUsage`
CREATE TABLE `rawUsage` (
  `title` varchar(255) DEFAULT NULL,
  `publisher` varchar(255) DEFAULT NULL,
  `platform` varchar(255) DEFAULT NULL,
  `doi` varchar(255) DEFAULT NULL,
  `identifier` varchar(255) DEFAULT NULL,
  `issn` varchar(255) DEFAULT NULL,
  `eIssn` varchar(255) DEFAULT NULL,
  `reportingPeriodTotal` varchar(255) DEFAULT NULL,
  `reportingPeriodHtml` varchar(255) DEFAULT NULL,
  `reportingPeriodPdf` varchar(255) DEFAULT NULL,
  `jan` varchar(255) DEFAULT NULL,
  `feb` varchar(255) DEFAULT NULL,
  `mar` varchar(255) DEFAULT NULL,
  `apr` varchar(255) DEFAULT NULL,
  `may` varchar(255) DEFAULT NULL,
  `jun` varchar(255) DEFAULT NULL,
  `jul` varchar(255) DEFAULT NULL,
  `aug` varchar(255) DEFAULT NULL,
  `sep` varchar(255) DEFAULT NULL,
  `oct` varchar(255) DEFAULT NULL,
  `nov` varchar(255) DEFAULT NULL,
  `dec` varchar(255) DEFAULT NULL,
  `year` varchar(255) DEFAULT NULL,
  KEY `issnIndx` (`issn`),
  KEY `eIssnIndx` (`eIssn`),
  KEY `year` (`year`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Create syntax for TABLE 'rawWorkflows'
CREATE TABLE IF NOT EXISTS `rawWorkflows` (
  `account` varchar(255) DEFAULT NULL,
  `subAccount` varchar(255) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `year` varchar(255) DEFAULT NULL,
  `price` varchar(255) DEFAULT NULL,
  `orderNumber` varchar(255) DEFAULT NULL,
  `titleControl` varchar(255) DEFAULT NULL,
  `extra` varchar(255) DEFAULT NULL,
  `issn` varchar(255) DEFAULT NULL,
  `callNumber` varchar(255) DEFAULT NULL,
  `notes` varchar(255) DEFAULT NULL,
  KEY `issnIndx` (`issn`),
  KEY `titleControlIndx` (`titleControl`),
  KEY `subAccountIndx` (`subAccount`),
  KEY `yearIndx` (`year`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
