-- Create syntax for TABLE 'rawAsjc'
CREATE TABLE IF NOT EXISTS `rawAsjc` (
  `description` varchar(255) DEFAULT NULL,
  `code` int(11) DEFAULT NULL,
  KEY `codeIndx` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Create syntax for TABLE 'rawConferenceProceedings'
CREATE TABLE IF NOT EXISTS `rawConferenceProceedings` (
  `sourceRecordId` bigint(11) DEFAULT NULL,
  `sourceTitle` varchar(255) DEFAULT NULL,
  `coverage` int(11) DEFAULT NULL,
  `issn` varchar(255) DEFAULT NULL,
  `addedNovember2015` varchar(255) DEFAULT NULL,
  `snip2013` decimal(10,3) DEFAULT NULL,
  `ipp2013` decimal(10,3) DEFAULT NULL,
  `sjr2013` decimal(10,3) DEFAULT NULL,
  `snip2014` decimal(10,3) DEFAULT NULL,
  `ipp2014` decimal(10,3) DEFAULT NULL,
  `sjr2014` decimal(10,3) DEFAULT NULL,
  `snip2015` decimal(10,3) DEFAULT NULL,
  `ipp2015` decimal(10,3) DEFAULT NULL,
  `sjr2015` decimal(10,3) DEFAULT NULL,
  `asjc` varchar(255) DEFAULT NULL,
  KEY `sourceRecordIdIndx` (`sourceRecordId`),
  KEY `issnIndx` (`issn`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Create syntax for TABLE 'rawConferenceProceedingsBackfiles'
CREATE TABLE IF NOT EXISTS `rawConferenceProceedingsBackfiles` (
  `sourceRecordId` bigint(11) DEFAULT NULL,
  `sourceTitle` varchar(255) DEFAULT NULL,
  `coverage` varchar(255) DEFAULT NULL,
  `issn` varchar(255) DEFAULT NULL,
  `asjc` varchar(255) DEFAULT NULL,
  KEY `sourceRecordIdIndx` (`sourceRecordId`),
  KEY `issnIndx` (`issn`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Create syntax for TABLE 'rawScimago'
CREATE TABLE IF NOT EXISTS `rawScimago` (
  `rank` int(11) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `type` varchar(255) DEFAULT NULL,
  `issn` varchar(255) DEFAULT NULL,
  `sjr` decimal(10,3) DEFAULT NULL,
  `sjrBestQuartile` varchar(255) DEFAULT NULL,
  `hIndex` int(11) DEFAULT NULL,
  `totalDocs2015` int(11) DEFAULT NULL,
  `totalDocs3Years` int(11) DEFAULT NULL,
  `totalRefs` int(11) DEFAULT NULL,
  `totalCites3Years` int(11) DEFAULT NULL,
  `citableDocs3Years` int(11) DEFAULT NULL,
  `citesPerDoc2Years` decimal(10,2) DEFAULT NULL,
  `refsPerDoc` decimal(10,2) DEFAULT NULL,
  `country` varchar(255) DEFAULT NULL,
  KEY `issnIndx` (`issn`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Create syntax for TABLE 'rawScopusSources'
CREATE TABLE IF NOT EXISTS `rawScopusSources` (
  `sourceRecordId` bigint(11) DEFAULT NULL,
  `sourceTitle` varchar(255) DEFAULT NULL,
  `issn` varchar(255) DEFAULT NULL,
  `eIssn` varchar(255) DEFAULT NULL,
  `coverage` varchar(255) DEFAULT NULL,
  `status` varchar(255) DEFAULT NULL,
  `snip2013` decimal(10,3) DEFAULT NULL,
  `ipp2013` decimal(10,3) DEFAULT NULL,
  `sjr2013` decimal(10,3) DEFAULT NULL,
  `snip2014` decimal(10,3) DEFAULT NULL,
  `ipp2014` decimal(10,3) DEFAULT NULL,
  `sjr2014` decimal(10,3) DEFAULT NULL,
  `snip2015` decimal(10,3) DEFAULT NULL,
  `ipp2015` decimal(10,3) DEFAULT NULL,
  `sjr2015` decimal(10,3) DEFAULT NULL,
  `medlineSourced` varchar(255) DEFAULT NULL,
  `openAccess` varchar(255) DEFAULT NULL,
  `articlesInPress` varchar(255) DEFAULT NULL,
  `addedMay2016` varchar(255) DEFAULT NULL,
  `sourceType` varchar(255) DEFAULT NULL,
  `titleHistoryIndication` varchar(255) DEFAULT NULL,
  `relatedTitle1` varchar(255) DEFAULT NULL,
  `relatedTitle2` varchar(255) DEFAULT NULL,
  `relatedTitle3` varchar(255) DEFAULT NULL,
  `relatedTitle4` varchar(255) DEFAULT NULL,
  `publisher` varchar(255) DEFAULT NULL,
  `publisherImprints` varchar(255) DEFAULT NULL,
  `publicationLocation` varchar(255) DEFAULT NULL,
  `asjc` varchar(255) DEFAULT NULL,
  `topLevelLifeSciences` varchar(255) DEFAULT NULL,
  `topLevelSocialSciences` varchar(255) DEFAULT NULL,
  `topLevelPhysicalSciences` varchar(255) DEFAULT NULL,
  `topLevelHealthSciences` varchar(255) DEFAULT NULL,
  `general` varchar(255) DEFAULT NULL,
  `agriculturalBiologicalSciences` varchar(255) DEFAULT NULL,
  `artsHumanities` varchar(255) DEFAULT NULL,
  `biochemistryGeneticsMolecularBiology` varchar(255) DEFAULT NULL,
  `businessManagementAccounting` varchar(255) DEFAULT NULL,
  `chemicalEngineering` varchar(255) DEFAULT NULL,
  `chemistry` varchar(255) DEFAULT NULL,
  `computerScience` varchar(255) DEFAULT NULL,
  `decisionSciences` varchar(255) DEFAULT NULL,
  `earthPlanetarySciences` varchar(255) DEFAULT NULL,
  `economicsEconometricsFinance` varchar(255) DEFAULT NULL,
  `energy` varchar(255) DEFAULT NULL,
  `engineering` varchar(255) DEFAULT NULL,
  `environmentalScience` varchar(255) DEFAULT NULL,
  `immunologyMicrobiology` varchar(255) DEFAULT NULL,
  `materialsScience` varchar(255) DEFAULT NULL,
  `mathematics` varchar(255) DEFAULT NULL,
  `medicine` varchar(255) DEFAULT NULL,
  `neuroscience` varchar(255) DEFAULT NULL,
  `nursing` varchar(255) DEFAULT NULL,
  `pharmacologyToxicologyPharmaceutics` varchar(255) DEFAULT NULL,
  `physicsAstronomy` varchar(255) DEFAULT NULL,
  `psychology` varchar(255) DEFAULT NULL,
  `socialSciences` varchar(255) DEFAULT NULL,
  `veterinary` varchar(255) DEFAULT NULL,
  `dentistry` varchar(255) DEFAULT NULL,
  `healthProfessions` varchar(255) DEFAULT NULL,
  KEY `sourceRecordIdIndx` (`sourceRecordId`),
  KEY `issnIndx` (`issn`),
  KEY `eIssnIndx` (`eIssn`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Create syntax for TABLE 'rawSfx'
CREATE TABLE IF NOT EXISTS `rawSfx` (
  `sortableTitle` varchar(255) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `titleNonFilingCharacter` int(11) DEFAULT NULL,
  `issn` varchar(255) DEFAULT NULL,
  `objectId` bigint(30) DEFAULT NULL,
  `targetPublicName` varchar(255) DEFAULT NULL,
  `threshold` varchar(255) DEFAULT NULL,
  `eIssn` varchar(255) DEFAULT NULL,
  `abbreviatedTitle` mediumtext,
  `targetServiceType` varchar(255) DEFAULT NULL,
  `lccn` varchar(255) DEFAULT NULL,
  `objectPortfolioId` bigint(30) DEFAULT NULL,
  `856u` varchar(255) DEFAULT NULL,
  `856y` varchar(255) DEFAULT NULL,
  `856a` varchar(255) DEFAULT NULL,
  `245h` varchar(255) DEFAULT NULL,
  `localThreshold` varchar(255) DEFAULT NULL,
  `globalThreshold` varchar(255) DEFAULT NULL,
  `targetId` bigint(11) DEFAULT NULL,
  `targetServiceId` bigint(11) DEFAULT NULL,
  `objectPortfolioId2` bigint(30) DEFAULT NULL,
  `categories` mediumtext,
  `localAttribute` varchar(255) DEFAULT NULL,
  `isbn` varchar(255) DEFAULT NULL,
  `eIsbn` varchar(255) DEFAULT NULL,
  `publisher` varchar(255) DEFAULT NULL,
  `publicationLocation` varchar(255) DEFAULT NULL,
  `publicationDate` varchar(255) DEFAULT NULL,
  `objectType` varchar(255) DEFAULT NULL,
  `activationStatus` varchar(255) DEFAULT NULL,
  `instituteId` varchar(255) DEFAULT NULL,
  `instituteName` varchar(255) DEFAULT NULL,
  `instituteAvailability` varchar(255) DEFAULT NULL,
  `language` varchar(255) DEFAULT NULL,
  `mainTitleCjk` varchar(255) DEFAULT NULL,
  `fullOriginalTitleCjk` varchar(255) DEFAULT NULL,
  `additionalIsbns` varchar(255) DEFAULT NULL,
  `additionalEIsbns` varchar(255) DEFAULT NULL,
  `author` varchar(255) DEFAULT NULL,
  `owner` varchar(255) DEFAULT NULL,
  `thresholdLocal` varchar(255) DEFAULT NULL,
  `parseParam` varchar(255) DEFAULT NULL,
  `isFree` varchar(255) DEFAULT NULL,
  KEY `issnIndx` (`issn`),
  KEY `eIssnIndx` (`eIssn`),
  KEY `lccnIndx` (`lccn`),
  KEY `objectId` (`objectId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Create syntax for TABLE 'rawSnip'
CREATE TABLE IF NOT EXISTS `rawSnip` (
  `sourceRecordId` bigint(11) DEFAULT NULL,
  `sourceTitle` varchar(255) DEFAULT '',
  `issn` varchar(255) DEFAULT NULL,
  `eIssn` varchar(255) DEFAULT NULL,
  `publisher` varchar(255) DEFAULT NULL,
  `publisherImprints` varchar(255) DEFAULT NULL,
  `publicationLocation` varchar(255) DEFAULT NULL,
  `snip1999` decimal(10,3) DEFAULT NULL,
  `ipp1999` decimal(10,3) DEFAULT NULL,
  `sjr1999` decimal(10,3) DEFAULT NULL,
  `snip2000` decimal(10,3) DEFAULT NULL,
  `ipp2000` decimal(10,3) DEFAULT NULL,
  `sjr2000` decimal(10,3) DEFAULT NULL,
  `snip2001` decimal(10,3) DEFAULT NULL,
  `ipp2001` decimal(10,3) DEFAULT NULL,
  `sjr2001` decimal(10,3) DEFAULT NULL,
  `snip2002` decimal(10,3) DEFAULT NULL,
  `ipp2002` decimal(10,3) DEFAULT NULL,
  `sjr2002` decimal(10,3) DEFAULT NULL,
  `snip2003` decimal(10,3) DEFAULT NULL,
  `ipp2003` decimal(10,3) DEFAULT NULL,
  `sjr2003` decimal(10,3) DEFAULT NULL,
  `snip2004` decimal(10,3) DEFAULT NULL,
  `ipp2004` decimal(10,3) DEFAULT NULL,
  `sjr2004` decimal(10,3) DEFAULT NULL,
  `snip2005` decimal(10,3) DEFAULT NULL,
  `ipp2005` decimal(10,3) DEFAULT NULL,
  `sjr2005` decimal(10,3) DEFAULT NULL,
  `snip2006` decimal(10,3) DEFAULT NULL,
  `ipp2006` decimal(10,3) DEFAULT NULL,
  `sjr2006` decimal(10,3) DEFAULT NULL,
  `snip2007` decimal(10,3) DEFAULT NULL,
  `ipp2007` decimal(10,3) DEFAULT NULL,
  `sjr2007` decimal(10,3) DEFAULT NULL,
  `snip2008` decimal(10,3) DEFAULT NULL,
  `ipp2008` decimal(10,3) DEFAULT NULL,
  `sjr2008` decimal(10,3) DEFAULT NULL,
  `snip2009` decimal(10,3) DEFAULT NULL,
  `ipp2009` decimal(10,3) DEFAULT NULL,
  `sjr2009` decimal(10,3) DEFAULT NULL,
  `snip2010` decimal(10,3) DEFAULT NULL,
  `ipp2010` decimal(10,3) DEFAULT NULL,
  `sjr2010` decimal(10,3) DEFAULT NULL,
  `snip2011` decimal(10,3) DEFAULT NULL,
  `ipp2011` decimal(10,3) DEFAULT NULL,
  `sjr2011` decimal(10,3) DEFAULT NULL,
  `snip2012` decimal(10,3) DEFAULT NULL,
  `ipp2012` decimal(10,3) DEFAULT NULL,
  `sjr2012` decimal(10,3) DEFAULT NULL,
  `snip2013` decimal(10,3) DEFAULT NULL,
  `ipp2013` decimal(10,3) DEFAULT NULL,
  `sjr2013` decimal(10,3) DEFAULT NULL,
  `snip2014` decimal(10,3) DEFAULT NULL,
  `ipp2014` decimal(10,3) DEFAULT NULL,
  `sjr2014` decimal(10,3) DEFAULT NULL,
  `snip2015` decimal(10,3) DEFAULT NULL,
  `ipp2015` decimal(10,3) DEFAULT NULL,
  `sjr2015` decimal(10,3) DEFAULT NULL,
  `topLevelLifeSciences` varchar(255) DEFAULT NULL,
  `topLevelSocialSciences` varchar(255) DEFAULT NULL,
  `topLevelPhysicalSciences` varchar(255) DEFAULT NULL,
  `topLevelHealthSciences` varchar(255) DEFAULT NULL,
  `general` varchar(255) DEFAULT NULL,
  `agriculturalBiologicalSciences` varchar(255) DEFAULT NULL,
  `artsHumanities` varchar(255) DEFAULT NULL,
  `biochemistryGeneticsMolecularBiology` varchar(255) DEFAULT NULL,
  `businessManagementAccounting` varchar(255) DEFAULT NULL,
  `chemicalEngineering` varchar(255) DEFAULT NULL,
  `chemistry` varchar(255) DEFAULT NULL,
  `computerScience` varchar(255) DEFAULT NULL,
  `decisionSciences` varchar(255) DEFAULT NULL,
  `earthPlanetarySciences` varchar(255) DEFAULT NULL,
  `economicsEconometricsFinance` varchar(255) DEFAULT NULL,
  `energy` varchar(255) DEFAULT NULL,
  `engineering` varchar(255) DEFAULT NULL,
  `environmentalScience` varchar(255) DEFAULT NULL,
  `immunologyMicrobiology` varchar(255) DEFAULT NULL,
  `materialsScience` varchar(255) DEFAULT NULL,
  `mathematics` varchar(255) DEFAULT NULL,
  `medicine` varchar(255) DEFAULT NULL,
  `neuroscience` varchar(255) DEFAULT NULL,
  `nursing` varchar(255) DEFAULT NULL,
  `pharmacologyToxicologyPharmaceutics` varchar(255) DEFAULT NULL,
  `physicsAstronomy` varchar(255) DEFAULT NULL,
  `psychology` varchar(255) DEFAULT NULL,
  `socialSciences` varchar(255) DEFAULT NULL,
  `veterinary` varchar(255) DEFAULT NULL,
  `dentistry` varchar(255) DEFAULT NULL,
  `healthProfessions` varchar(255) DEFAULT NULL,
  `asjc` varchar(255) DEFAULT NULL,
  KEY `issnIndx` (`issn`),
  KEY `eIssnIndx` (`eIssn`),
  KEY `sourceRecordIdIndx` (`sourceRecordId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Create syntax for TABLE `rawUsage`
CREATE TABLE `rawUsage` (
  `title` varchar(255) DEFAULT NULL,
  `publisher` varchar(255) DEFAULT NULL,
  `platform` varchar(255) DEFAULT NULL,
  `doi` varchar(255) DEFAULT NULL,
  `identifier` varchar(255) DEFAULT NULL,
  `issn` varchar(255) DEFAULT NULL,
  `eIssn` varchar(255) DEFAULT NULL,
  `reportingPeriodTotal` varchar(255) DEFAULT NULL,
  `reportingPeriodHtml` varchar(255) DEFAULT NULL,
  `reportingPeriodPdf` varchar(255) DEFAULT NULL,
  `jan` int(11) DEFAULT NULL,
  `feb` int(11) DEFAULT NULL,
  `mar` int(11) DEFAULT NULL,
  `apr` int(11) DEFAULT NULL,
  `may` int(11) DEFAULT NULL,
  `jun` int(11) DEFAULT NULL,
  `jul` int(11) DEFAULT NULL,
  `aug` int(11) DEFAULT NULL,
  `sep` int(11) DEFAULT NULL,
  `oct` int(11) DEFAULT NULL,
  `nov` int(11) DEFAULT NULL,
  `dec` int(11) DEFAULT NULL,
  `year` year(4) DEFAULT NULL,
  KEY `issnIndx` (`issn`),
  KEY `eIssnIndx` (`eIssn`),
  KEY `year` (`year`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Create syntax for TABLE 'rawWorkflows'
CREATE TABLE IF NOT EXISTS `rawWorkflows` (
  `account` bigint(17) DEFAULT NULL,
  `subAccount` int(5) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `year` year(4) DEFAULT NULL,
  `price` varchar(255) DEFAULT NULL,
  `orderNumber` varchar(255) DEFAULT NULL,
  `titleControl` varchar(255) DEFAULT NULL,
  `extra` varchar(255) DEFAULT NULL,
  `issn` varchar(255) DEFAULT NULL,
  `callNumber` varchar(255) DEFAULT NULL,
  `notes` varchar(255) DEFAULT NULL,
  KEY `issnIndx` (`issn`),
  KEY `titleControlIndx` (`titleControl`),
  KEY `subAccountIndx` (`subAccount`),
  KEY `yearIndx` (`year`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
